### ISSUE TITLE
arubaoss_reboot  "Could not get devcie status. Not rebooted!"

### ISSUE THREAD

**Issue by robertpriedl** [aruba/aruba-ansible-modules#110] opened 2020-06-24 08:31 UTC
ansible version: 2.9
python version: 3.6

I am getting this error when running arubaoss_reboot. The error message is "Could not get devcie status. Not rebooted!"
Other arubaoss_ Tasks are working (like arubaoss_interface, arubaoss_vlan..)

My **inventory** with connection settings:
```
all:
  hosts:
    switch001:
      ansible_host: 10.20.220.200
      ansible_network_os: arubaoss
      ansible_connection: local
      ansible_user: test
      ansible_password: test123
```

My **playbook**:
```
---
- hosts: all
  tasks:
  - name: reboot device
    arubaoss_reboot:
      boot_image: BI_SECONDARY_IMAGE
      is_wait: False
```

the vvvv output of the playbook:
```connection transport is aossapi for 10.20.220.200
None is not valid api version. using aossapi v6.0 instead
<10.20.220.200> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.20.220.200> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.20.220.200> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1592990341.4901884-11386-128318066366902 && echo ansible-tmp-1592990341.4901884-11386-128318066366902="` echo /root/.ansible/tmp/ansible-tmp-1592990341.4901884-11386-128318066366902 `" ) && sleep 0'
Using module file /usr/lib/python3.6/site-packages/ansible/modules/network/arubaoss/arubaoss_reboot.py
<10.20.220.200> PUT /root/.ansible/tmp/ansible-local-112983_jhgncf/tmpbbjkxw7g TO /root/.ansible/tmp/ansible-tmp-1592990341.4901884-11386-128318066366902/AnsiballZ_arubaoss_reboot.py
<10.20.220.200> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1592990341.4901884-11386-128318066366902/ /root/.ansible/tmp/ansible-tmp-1592990341.4901884-11386-128318066366902/AnsiballZ_arubaoss_reboot.py && sleep 0'
<10.20.220.200> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1592990341.4901884-11386-128318066366902/AnsiballZ_arubaoss_reboot.py && sleep 0'
<10.20.220.200> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1592990341.4901884-11386-128318066366902/ > /dev/null 2>&1 && sleep 0'
fatal: [switch001]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "v7.0",
            "boot_image": "BI_SECONDARY_IMAGE",
            "host": "10.20.220.200",
            "is_wait": false,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 80,
            "provider": {
                "api_version": null,
                "host": "10.20.220.200",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 80,
                "ssh_keyfile": null,
                "timeout": 30,
                "transport": "aossapi",
                "use_proxy": false,
                "use_ssl": false,
                "username": "test",
                "validate_certs": false
            },
            "ssh_keyfile": null,
            "timeout": 30,
            "use_ssl": false,
            "username": "test",
            "validate_certs": false
        }
    },
    "msg": "Could not get devcie status. Not rebooted!"
```
How can i getting the reboot working?

robert

**Comment by tchiapuziowong** [comment] 2020-06-24 15:50
Hi @robertpriedl ! Could you please provide the switch model and firmware you're using?

**Comment by tchiapuziowong** [comment] 2020-06-25 16:04
Hi @robertpriedl ! We're looking into this issue and will an update soon!

Thank you @alagoutte for your contribution and troubleshooting! At this time I'm going to hold on the pull-request due to possible merge conflict but will merge once the fix is pushed!

**Comment by tchiapuziowong** [comment] 2020-07-10 17:27
Hi @robertpriedl ! We've pushed a fix to this module - please pull and reinstall the modules and let us know if that resolved your issue! Also if you're interested we have the aos-switch Ansible collection if you're using Ansible version 2.9 and higher : https://github.com/aruba/aos-switch-ansible-collection

**Comment by robertpriedl** [comment] 2020-07-10 19:30
Hi @tchiapuziowong ,
thank you, the reboot is now happening, but i got folowing error:
`fatal: [switch001]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "v7.0",
            "boot_image": "BI_SECONDARY_IMAGE",
            "host": "10.x.x.x",
            "is_wait": true,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 80,
            "provider": {
                "api_version": null,
                "host": "10.x.x.x",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": 80,
                "ssh_keyfile": null,
                "timeout": 30,
                "transport": "aossapi",
                "use_proxy": false,
                "use_ssl": false,
                "username": "test",
                "validate_certs": false
            },
            "ssh_keyfile": null,
            "timeout": 30,
            "use_ssl": false,
            "username": "test",
            "validate_certs": false
        }
    },
    "msg": "Device reboot failed.",
    "total_time": 402
}
`

**Comment by tchiapuziowong** [comment] 2020-07-10 20:15
Ah I see so just to clarify your switch is rebooting successfully even when receiving this error?

**Comment by robertpriedl** [comment] 2020-07-11 05:45
Yes, but I have to wait til Monday for the network admin, to check the correct boot image and check the switch, if it is OK.

**Comment by tchiapuziowong** [comment] 2020-07-14 18:00
Hi @robertpriedl could you provide the firmware version you're running - it seems like you provided the ROM version. If you execute `show flash` on the switch you should see which image you're running

**Comment by robertpriedl** [comment] 2020-07-15 07:51
Hi @tchiapuziowong,
my show flash output:
```
Image             Size (bytes) Date     Version
----------------- ------------ -------- --------------
Primary Image    :    30041199 04/17/20 WC.16.10.0007
Secondary Image  :    29823971 03/30/20 WC.16.09.0010

Boot ROM Version
----------------
Primary Boot ROM Version   : WC.17.02.0006
Secondary Boot ROM Version : WC.17.02.0006

Default Boot Image   : Secondary
Default Boot ROM     : Primary

```

**Comment by tchiapuziowong** [comment] 2020-07-15 17:39
Hi @robertpriedl ! I've tested with a stack with those images and I wasn't able to reproduce the issue but I noticed that the playbook had `is_wait: False` originally but in the playbook with the error it had `is_wait: true` - could you try again with `is_wait: False`? since this is a stack it may take more time to reboot all the members

**Comment by robertpriedl** [comment] 2020-07-16 13:10
Hi @tchiapuziowong with ìs_wait: true` the error still occurs. On the switch i get folowing message at login:
```
System went down:  07/16/20 13:00:52
Saved crash information:
Press any key to continueer reboot
```

**Comment by tchiapuziowong** [comment] 2020-07-16 15:26
Apologies @robertpriedl I believe the error might be because you should set 'is_wait: false' - if you change that value does the error still occur?

**Closed** 2020-07-29 18:39 UTC
