### ISSUE TITLE
"Connection failure: Remote end closed connection without response during login"

### ISSUE THREAD

**Issue by mghiglieri** [aruba/aruba-ansible-modules#117] opened 2020-09-09 09:47 UTC
Hello,

I'm trying to automate the configuration of Aruba-Switches. 

Ansible and Python states that "Connection failure: Remote end closed connection without response". However a curl command:
 `curl --noproxy xx.xx.xx.xx -X POST http://xx.xx.xx.xx/rest/v6.0/login-sessions -d '{"userName":"username", "password":"password"}' -k`
=>
`{"payloadSize":65536,"uri":"/login-sessions","cookie":"sessionId=Pv3HsW3svqkmTX69Jti1aCjlCpJctrvvLmrp1GgfZSqumw9UQnfxPEMyrlXnYzH"}`
works.

I already tested it with a little Python script and it seems that the Python-Library times out...

```
import json
import requests


def login_os(data, url):
    username = data['user']
    password = data['password']
    params = {'userName': username, 'password': password}
    body=json.dumps(params)
    proxies = {'http': None, 'https': None}
    url_login = url + "login-sessions"
    print(url_login)
    response = requests.post(url_login, verify=False, json=params, proxies=proxies)
    if response.status_code == 201:
        print("Login to switch: {} is successful".format(url_login))
        session = response.json()
        r_cookie = session['cookie']
        return r_cookie
    else:
        print("Login to switch failed")
```

Does anybody know how to solve the issue?

Switch: Aruba JL356A 2540-24G-PoE+-4SFP+ Switch

```
show version

Image stamp:    /ws/swbuildm/rel_ajanta_qaoff/code/build/cpm(swbuildm_rel_ajanta_qaoff_rel_ajanta)
                Aug 21 2020 11:10:50
                YC.16.10.0010
                502
Boot Image:     Primary

Boot ROM Version:    YC.16.01.0002
Active Boot ROM:     Primary
```

**Comment by tchiapuziowong** [comment] 2020-09-09 15:29
Hello! Since you're experiencing this both in python and Ansible it's most likely an environment issue. Here are a few questions that can help narrow down the issue:

-  Are you using any authentication servers that could be preventing the REST API request? TACACs+ , RADIUS?
- Is REST API enabled on the switch? enter `show web-management ssl`
- Is your switch managed by Central?

**Comment by mghiglieri** [comment] 2020-09-10 07:10
Hello,

thanks for helping. The strange thing is, that it is working with curl every time. 

- It's just a single Switch without any additional authentication services like TACACs+ or RADIUS. I'm using a manager account on the switch to connect. It is not managed by Central.
REST API is enable:

```
show web-management

 Web Management - Server Configuration

  HTTP Access    : Enabled
  HTTPS Access   : Enabled
  SSL Port       : 443
  Idle Timeout   : 600 seconds
  Management URL : http://h17007.www1.hpe.com/device_help
  Support URL    : https://www.hpe.com/us/en/networking.html
  User Interface : Improved
```
```
show rest-interface

 REST Interface - Server Configuration

  REST Interface            : Enabled
  REST Operational Status   : Up
  REST Session Idle Timeout : 600 seconds
  HTTP Access               : Enabled
  HTTPS Access              : Enabled
  SSL Port                  : 443
```
It doesn't matter if I connect via HTTP or HTTPS. 

I have double-checked the following things already:
- Client in the same network...same issue
- when I just send a request without any POST data it is answering pretty fast. It seems like an issue with the switch.
- I experienced the same issue on another switch, so maybe firmware issues ?

I just tried to login in a loop and surprisingly some requests were successful. It seems that the switch closes the connection when it cannot answer in a specific time range. Is there any timeout that can be increased?

Thanks
Marco

**Comment by alagoutte** [comment] 2020-09-11 12:34
Hi Marco,

Can you try to downgrade firmware to 16.10.0007 ? i get the same issue with PS5....

**Comment by tchiapuziowong** [comment] 2020-09-11 15:57
Hi Marco!

For your requests.post , instead of setting json can you set the data parameter? like so:
`response = requests.post(url_login, verify=False, data=json.dumps(params), proxies=proxies)`

and see if that makes any changes?

**Comment by tchiapuziowong** [comment] 2020-09-11 15:58
actually looking at your code you already set `body=json.dumps(params)` so then try:  
`response = requests.post(url_login, verify=False, data=body, proxies=proxies)`

**Comment by mghiglieri** [comment] 2020-09-14 11:30
@tchiapuziowong: Thanks. But have already checked both options `data=body` and `json=params`. No difference.
@alagoutte Thanks. Will check a downgrade...I'm let you know if that fixes the issue.

**Comment by mghiglieri** [comment] 2020-09-16 09:48
@alagoutte It is indeed the firmware. 16.10.0007 is working smoothly.

Does anybody now when the newest FW is fixed ?

**Comment by alagoutte** [comment] 2020-09-17 12:10
> 
> 
> @alagoutte It is indeed the firmware. 16.10.0007 is working smoothly.
> 
> Does anybody know when the newest FW will be fixed ?

i known only the issue is reported to Aruba and i hope it will be fixed on next firmware...

**Comment by tchiapuziowong** [comment] 2020-11-05 19:35
Hello! 16.10.0011 has been release and includes fixes for this issue, please update your devices and verify the behavior is nolonger seen! @mghiglieri @alagoutte

**Closed** 2021-06-29 19:16 UTC

**Comment by mghiglieri** [comment] 2024-08-21 14:09
This error seems to be back.

('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

FW YC.16.11.0020

**Comment by mghiglieri** [comment] 2024-11-20 07:59
> Having the same problem with WC.16.11.0020 Patchnotes of WC.16.11.0021:
> 
> > Symptom: Some users do not receive
> > HTTP response from the switch.
> > Scenario:This issue occurred when HTTP
> > requests were sent using Ansible scripts
> > and the Ansible client interface
> > experienced connection failures.
> 
> I will upgrade and test

We **couldn't resolve** the issue with upgrading to WC.16.11.0021. 
What resolved these issues for us was to rewrite the entire library not using requests. We use curl instead - works smoothly so far.

**Comment by jovial-blackwell** [comment] 2024-11-22 07:38
> > Having the same problem with WC.16.11.0020 Patchnotes of WC.16.11.0021:
> > > Symptom: Some users do not receive
> > > HTTP response from the switch.
> > > Scenario:This issue occurred when HTTP
> > > requests were sent using Ansible scripts
> > > and the Ansible client interface
> > > experienced connection failures.
> > 
> > 
> > I will upgrade and test
> 
> We **couldn't resolve** the issue with upgrading to WC.16.11.0021. What resolved these issues for us was to rewrite the entire library not using requests. We use curl instead - works smoothly so far.

Is this Library open source? If so could you link me to it? Thx
