### ISSUE TITLE
ArubaOSS module not working with UT_OPERATOR on switches

### ISSUE THREAD

**Issue by FloLaco** [aruba/aruba-ansible-modules#34] opened 2019-07-31 09:15 UTC
If the switch have a user UT_OPERATOR configured, each API call need to be authenticated, even the '/rest/version'.
But the `get_config()` or `run_commands()` refers to `get_version()` which does not use `sessionId` cookies.

```
ASW2_ARU# sh ver

Image stamp:    /ws/swbuildm/rel_yakima_qaoff/code/build/lvm(swbuildm_rel_yakima_qaoff_rel_yakima)
                May  2 2019 19:24:38
                WC.16.08.0003
                692
Boot Image:     Primary

Boot ROM Version:    WC.17.02.0006
Active Boot ROM:     Primary

ASW2_ARU(config)# sh run struc | inc pass
password manager user-name "root" sha1 "XXXXX"
```

```
$ curl -X GET http://10.215.151.41:80/rest/version             
{"uri":"/version","collection_result":{"total_elements_count":5,"filtered_elements_count":5},"version_element":[{"version":"v3.0"},{"version":"v3.1"},{"version":"v4.0"},{"version":"v5.0"},{"version":"v6.0"}]}
```

```
ASW2_ARU(config)# password operator user-name "rezo" sha1 "YYYYY"
ASW2_ARU(config)# 
ASW2_ARU(config)# 
ASW2_ARU(config)# sh run struc | inc pass
password operator user-name "rezo" sha1 "YYYY"
password manager user-name "root" sha1 "XXXX"
```

```
$ curl -X GET http://10.215.151.41:80/rest/version
<HTML><TITLE>400 Bad Request</TITLE><H1>Bad Request</H1>Please login to access the resource.<P></HTML>
```

**Comment by alagoutte** [comment] 2019-09-04 11:58
Hi,

Do you have try last firmware ? (because i remenber there is a fix for this)

**Comment by tchiapuziowong** [comment] 2019-09-05 16:44
This issue is resolved with the latest commit, confirmed with firmware versions 16.08 and 16.07 with 2930F: https://github.com/aruba/aruba-ansible-modules/commit/0e67c712c4e1f2b996e285880cc50019ef5870d6

**Closed by tchiapuziowong** 2019-09-05 16:44 UTC
